### ISSUE TITLE
Null objects break the the connector 

### ISSUE THREAD

**Issue by iowusu** [marklogic-community/kafka-marklogic-connector#8]
When a null object is sent to the connect it throws this error

ERROR WorkerSinkTask{id=marklogic-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:558)
java.lang.NullPointerException
        at com.marklogic.kafka.connect.sink.DefaultSinkRecordConverter.toContent(DefaultSinkRecordConverter.java:90)
        at com.marklogic.kafka.connect.sink.DefaultSinkRecordConverter.convert(DefaultSinkRecordConverter.java:68)
        at com.marklogic.kafka.connect.sink.MarkLogicSinkTask.lambda$put$0(MarkLogicSinkTask.java:123)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.marklogic.kafka.connect.sink.MarkLogicSinkTask.put(MarkLogicSinkTask.java:119)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by rjrudin** [comment]
It's valid for the Collection<SinkRecord> that's passed to a sink task in the "put" method to contain a null object?? 

That seems odd, I would have guessed that the Kafka connector framework would filter out null objects. 

In any event, this looks trivial to handle in the "put" method. I'm only wondering if it's worth logging that "null" was received. If we do, I'd guess that logging it at the "debug" level suffices.

**Comment by BillFarber** [comment]
Surprisingly, a message with a "null" value is possible and in fact is intentional, acting like a tombstone for log compaction (http://cloudurable.com/blog/kafka-architecture-log-compaction/index.html).
I have a solution locally, but haven't pushed it yet. I will soon.

**Comment by BillFarber** [comment]
Fixed in Release 1.1.0
